PPR_STATUS_SCHEDULED = "scheduled"
PPR_STATUS_IN_PROGRESS = "in_progress"
PPR_STATUS_VERIFIED = "verified"
PPR_STATUS_ARCHIVED = "archived"
PPR_STATUS_CANCELLED = "cancelled"

ACTIVE_PPR_STATUSES = {
    PPR_STATUS_SCHEDULED,
    PPR_STATUS_IN_PROGRESS,
    PPR_STATUS_VERIFIED,
}

PPR_STATUSES = ACTIVE_PPR_STATUSES | {PPR_STATUS_ARCHIVED, PPR_STATUS_CANCELLED}

NOTIFICATION_STATUS_PLANNED = "planned"
NOTIFICATION_STATUS_PROCESSING = "processing"
NOTIFICATION_STATUS_DELIVERY_UNKNOWN = "delivery_unknown"
NOTIFICATION_STATUS_SENT = "sent"
NOTIFICATION_STATUS_FAILED = "failed"
NOTIFICATION_STATUS_SKIPPED = "skipped"
NOTIFICATION_STATUS_CANCELLED = "cancelled"

NOTIFICATION_STATUSES = {
    NOTIFICATION_STATUS_PLANNED,
    NOTIFICATION_STATUS_PROCESSING,
    NOTIFICATION_STATUS_DELIVERY_UNKNOWN,
    NOTIFICATION_STATUS_SENT,
    NOTIFICATION_STATUS_FAILED,
    NOTIFICATION_STATUS_SKIPPED,
    NOTIFICATION_STATUS_CANCELLED,
}

LEGACY_NOTIFICATION_STATUS_CHECKED = "checked"
LEGACY_NOTIFICATION_STATUS_ERROR = "error"
